"""Agregar usuario_id a ventas para reportes por empleado

Revision ID: 2ac13e55b712
Revises: 91bbef1e9e65
Create Date: 2025-11-20 21:12:01.700118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ac13e55b712'
down_revision = '91bbef1e9e65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_ventas_usuario', 'usuarios', ['usuario_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ventas_usuario', type_='foreignkey')
        batch_op.drop_column('usuario_id')

    # ### end Alembic commands ###
