"""Agregar modelos Animal y Consulta para historias clínicas

Revision ID: agregar_animal_consulta
Revises: 2ac13e55b712
Create Date: 2025-01-20 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'agregar_animal_consulta'
down_revision = '2ac13e55b712'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = inspect(conn)
    tables = inspector.get_table_names()
    
    # Crear tabla animales
    if 'animales' not in tables:
        op.create_table('animales',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('nombre', sa.String(length=200), nullable=False),
            sa.Column('especie', sa.String(length=100), nullable=False),
            sa.Column('raza', sa.String(length=200), nullable=True),
            sa.Column('edad', sa.String(length=50), nullable=True),
            sa.Column('nombre_dueno', sa.String(length=200), nullable=False),
            sa.Column('telefono_dueno', sa.String(length=20), nullable=True),
            sa.Column('activo', sa.Boolean(), nullable=True),
            sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
            sa.Column('notas', sa.Text(), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )
    
    # Crear tabla consultas
    if 'consultas' not in tables:
        op.create_table('consultas',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('animal_id', sa.Integer(), nullable=False),
            sa.Column('fecha_consulta', sa.DateTime(), nullable=False),
            sa.Column('motivo', sa.Text(), nullable=False),
            sa.Column('diagnostico', sa.Text(), nullable=True),
            sa.Column('tratamiento', sa.Text(), nullable=True),
            sa.Column('observaciones', sa.Text(), nullable=True),
            sa.Column('venta_id', sa.Integer(), nullable=True),
            sa.Column('usuario_id', sa.Integer(), nullable=True),
            sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['animal_id'], ['animales.id'], ),
            sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
            sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ),
            sa.PrimaryKeyConstraint('id')
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consultas')
    op.drop_table('animales')
    # ### end Alembic commands ###

