"""Agregar modelo Categoria y relacion con Producto

Revision ID: fc1220adaf25
Revises: 
Create Date: 2025-11-17 12:08:40.012334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc1220adaf25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Verificar si la tabla categorias existe, si no, crearla
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    tables = inspector.get_table_names()
    
    if 'categorias' not in tables:
        op.create_table('categorias',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nombre', sa.String(length=100), nullable=False),
        sa.Column('descripcion', sa.Text(), nullable=True),
        sa.Column('activa', sa.Boolean(), nullable=True),
        sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('nombre')
        )
    
    # Verificar columnas existentes en productos
    productos_columns = [col['name'] for col in inspector.get_columns('productos')]
    
    # Luego modificar la tabla productos
    with op.batch_alter_table('productos', schema=None) as batch_op:
        # Solo agregar categoria_id si no existe
        if 'categoria_id' not in productos_columns:
            batch_op.add_column(sa.Column('categoria_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key('fk_productos_categoria', 'categorias', ['categoria_id'], ['id'])
        
        # Solo eliminar la columna categoria si existe
        if 'categoria' in productos_columns:
            batch_op.drop_column('categoria')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint('fk_productos_categoria', type_='foreignkey')
        batch_op.drop_column('categoria_id')
    
    # Eliminar la tabla categorias
    op.drop_table('categorias')

    # ### end Alembic commands ###
